### ISSUE TITLE
Beyond MX check

### ISSUE THREAD

**Issue by joaomilho** [martyndavies/legit#6]
Domains like `sharklasers.com` are well-known to belong to non legit senders – guerrilla mail in this case. Is there any plan in legit to go beyond MX to include blacklists and whatnot? Else, any suggestions?

Best!

**Comment by martyndavies** [comment]
I've recently been thinking about the possibility of expanding the feature set of this package to include the ability to run checks against other APIs that you might have access to, such as the ability to check against the Kickbox API (if you already have an API key for them), but then I wondered if there was really value in doing this and abstracting another layer on top of their API when you could just hit that directly.

Happy to hear thoughts on this!

**Comment by martyndavies** [comment]
After taking some time to review, ultimately this would be a cool feature but would rely on third party APIs in order to perform that check, and given the nature of the data being passed around (email addresses in this case) might cause all kinds of data protection issues. Additionally, there are a number of services that make this easy via API, such as Hetrix, so in this case it isn't something I'm going to add but thanks for the suggestion.
